version: '3'
services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile-nginx
        image: timings-nginx
        ports:
            - "127.0.0.1:7081:80"
        volumes:
            - code:/var/www/html/timings
        depends_on:
            - phpfpm
        restart: unless-stopped


    phpfpm:
        build: 
            context: .
            dockerfile: Dockerfile-phpfpm
            args:
                - NR_INSTALL_KEY
        image: timings-php_fpm
        volumes:
            - code:/var/www/html/timings
        expose:
            - 9000
        restart: unless-stopped

volumes:
    code:
    
